# Generated by Django 5.2.5 on 2025-08-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pdf_file',
            new_name='book_file',
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('HARDCOPY', 'Hardcopy')], default='PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='hardcopy_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='books.college')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.department'),
        ),
    ]
